$(function(){
	$('#agenda').click(function(){
		$('.container-fluid').load("src/pages/agenda/index.php")
	})
	$('#servicos').click(function(){
		$('.container-fluid').load("src/pages/servicos/index.php")
	})
	$('#profissionais').click(function(){
		$('.container-fluid').load("src/pages/profissionais/index.php")
	})
	$('#comandas').click(function(){
		$('.container-fluid').load("src/pages/comandas/index.php")
	})
});